version: '3'

services:
  nodejs:
    image: node:12
    container_name: busybox
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: /home/node/app/node_modules/.bin/node app.js
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: 